[profile.default]
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
solc_version = "0.8.26"
verbosity = 3
src = "src"
out = "out"
libs = ["lib", "node_modules"]

[fuzz] # Fuzzing configurations increased for more thorough testing
runs = 20000
dictionnary_weight = 60
include_storage = true
include_push_bytes = true
show_logs = true

[invariant] # Invariant configurations increased for more thorough testing
runs = 20000
call_override = true # useful for reentrancy checks
dictionnary_weight = 80 # this is the default value

[profile.ci]
fuzz = { runs = 200000, dictionnary_weight = 100, include_storage = true, include_push_bytes = true, show_logs = true }
invariant = { runs = 200000, depth = 5000, call_override = true, dictionnary_weight = 100, include_storage = true, include_push_bytes = true }


[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
    "@/=node_modules/@",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-std/=lib/forge-std/src/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
