[profile.default]
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
solc_version = "0.8.26"
verbosity = 3
src = "src"
out = "out"
libs = ["lib", "node_modules"]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
    "@/=node_modules/@",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "forge-std/=lib/forge-std/src/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
